// <auto-generated />
namespace Garage25.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class owner_is_person : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(owner_is_person));
        
        string IMigrationMetadata.Id
        {
            get { return "201611250944496_owner_is_person"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
