// <auto-generated />
namespace Garage25.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class m_Owner : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(m_Owner));
        
        string IMigrationMetadata.Id
        {
            get { return "201611250825036_m_Owner"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
