// <auto-generated />
namespace Garage2._5.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class RegNR : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RegNR));
        
        string IMigrationMetadata.Id
        {
            get { return "201611231348197_RegNR"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
